import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { OrbitEngine } from "../src/orchestration";
import { MemoryPersistence } from "../src/persistence";
import { createSampleBrief } from "../src/fixtures";
import { buildExport } from "../src/export";
let sequence = 0;
const clock = () => new Date("2026-10-03T12:00:00.000Z");
const engine = new OrbitEngine(new MemoryPersistence(), {
  delayMs: 0,
  clock,
  id: () => `sample-${String(++sequence).padStart(4, "0")}`,
});
await engine.initialize();
const created = await engine.createCampaign(createSampleBrief());
await engine.runCampaign(created.id);
for (const asset of engine.getSnapshot().campaigns[0].assets)
  await engine.approveAsset(created.id, asset.spec.id);
const output = buildExport(engine.getSnapshot().campaigns[0], clock);
const directory = fileURLToPath(
  new URL("../samples/approved-campaign/", import.meta.url),
);
await mkdir(directory, { recursive: true });
for (const [filename, bytes] of Object.entries(output.files))
  await writeFile(`${directory}/${filename}`, bytes);
await writeFile(
  `${directory}/PROVENANCE.md`,
  "# Approved sample packet\n\nGenerated by `npm run sample` using the actual typed Orbit engine, bundled fictional Aster Coffee Works fixtures, simulated local provider, deterministic validation and exact-version approvals. The fixed clock and sequential IDs make this checked-in example reproducible. No customer, runtime browser or production data is included.\n\nAll six images are original SVG review concepts. Copy CSV is a review artifact. Video output is a brief. The manifest references the reviewed versions and source-context IDs. This packet is not a complete Google Ads asset group and does not authorize publishing or spend.\n",
);
console.log(
  `Generated ${Object.keys(output.files).length} reviewed sample files and provenance note.`,
);
